GLOBAL_LIST_INIT(maint_ambience,list(
	'sound/ambience/ambimaint1.ogg',
	'sound/ambience/ambimaint2.ogg',
	'sound/ambience/ambimaint4.ogg',
	'sound/ambience/ambitech2.ogg',
	'sound/voice/lowHiss1.ogg',
	'sound/voice/lowHiss2.ogg',
	'sound/voice/lowHiss3.ogg',
	'sound/voice/lowHiss4.ogg',
	'sound/ambience/maintambience.ogg',
	'Maintrooms/sound/ambience/maintroomsambi1.ogg',
	'Maintrooms/sound/ambience/maintroomsambi2.ogg',
	'Maintrooms/sound/ambience/maintroomsambi3.ogg',
))
